<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ToolboxManager.PollingService</RootNamespace>
    <AssemblyName>ToolboxManager.PollingService</AssemblyName>
    <UserSecretsId>toolbox-manager-polling-service</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="3.7.400.46" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.14" />
    <PackageReference Include="NLog.Extensions.Hosting" Version="5.3.14" />
    <PackageReference Include="NLog.Targets.Seq" Version="4.0.1" />
  </ItemGroup>

</Project>
